name: Build C to WebAssembly and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        echo "source $PWD/emsdk_env.sh" >> $GITHUB_ENV

    - name: Compile C to WASM
      run: |
        source emsdk/emsdk_env.sh
        emcc docs/main.c -o docs/main.js -s WASM=1 -s MODULARIZE=1 -s 'ENVIRONMENT=web'

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
